name: Release Pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Build
        run: python -u .github/workflows/scripts/create_file.py

      - name: Test
        run: cat random_value.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: random_value.txt